// Generated by CoffeeScript 1.10.0
(function() {
  var assert, should;

  should = require('should');

  assert = require('assert');

  describe('Configuration', function() {
    return it('configures the application correctly.', function(done) {
      var config;
      done();
      config = require('../config/configuration');
      config.env.should.be.equal('local');
      return done();
    });
  });

}).call(this);

//# sourceMappingURL=test_configuration.js.map
