// Generated by CoffeeScript 1.10.0
(function() {
  var ArchiveSchema, Mongoose, ObjectId, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ObjectId = Mongoose.Schema.Types.ObjectId;

  ArchiveSchema = new Schema({
    key: String,
    session: String
  }, {
    strict: false
  });

  module.exports = {
    model: Mongoose.model("Archive", ArchiveSchema),
    schema: ArchiveSchema
  };

}).call(this);

//# sourceMappingURL=archive.js.map
