// Generated by CoffeeScript 1.10.0
(function() {
  var DeviceSchema, Mongoose, ObjectId, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ObjectId = Mongoose.Schema.Types.ObjectId;

  DeviceSchema = new Schema({
    deviceId: String
  }, {
    strict: false
  });

  module.exports = {
    model: Mongoose.model("Device", DeviceSchema),
    schema: DeviceSchema
  };

}).call(this);

//# sourceMappingURL=device.js.map
