// Generated by CoffeeScript 1.10.0
(function() {
  var Mongoose, ObjectId, PortalSchema, Schema;

  Mongoose = require('mongoose');

  Schema = require('mongoose').Schema;

  ObjectId = Mongoose.Schema.Types.ObjectId;

  PortalSchema = new Schema({
    portalId: String
  }, {
    strict: false
  });

  module.exports = {
    model: Mongoose.model("Portal", PortalSchema),
    schema: PortalSchema
  };

}).call(this);

//# sourceMappingURL=portal.js.map
